version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:  echo "done"
     #  - restore_cache:
     #      keys:
     #        # when lock file changes, use increasingly general patterns to restore cache
     #        - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
     #        - node-v1-{{ .Branch }}-
     #        - node-v1-
     #  - run: npm i
     #  - save_cache:
     #      paths:
     #        - ~/usr/local/lib/node_modules  # location depends on npm version
     #      key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
     # # run all linting and testing
     #  - run: npm run eslint
     #  - run: npm run stylelint

  deploy:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm run deploy $CIRCLE_TAG

workflows:
  version: 2
  build-and-version:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
